/****** Object:  Table [dbo].[AircraftStatuses]    Script Date: 20-07-2022 09:50:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AircraftStatuses](
	[Id] [tinyint] IDENTITY(1,1) NOT NULL,
	[Status] [varchar](50) NOT NULL,
	[Indicator] [varchar](15) NOT NULL,
	[CanFly] [bit] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_AircraftStatuses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


