INSERT INTO AIRCRAFTSTATUSES VALUES ('Ready For Flight', 'GREEN',1)
INSERT INTO AIRCRAFTSTATUSES VALUES ('Review Sqwaks', 'ORANGE',0)
INSERT INTO AIRCRAFTSTATUSES VALUES ('Inspections Required','YELLOW',0)
INSERT INTO AIRCRAFTSTATUSES VALUES ('Down for Maintenance','RED',0)




